export const homeObjOne = {
  id: "about",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "개구리 거래소",
  headline: " 무한한 정보제공과 상장된 가상화폐의 서비스 가능 경로 정보 제공",
  description:
    "  회원가입과 동시에 250$ 상당의 가상화폐 획득! 2021년도 내의 유일한 이벤트! 자신의 투자성향과 다양한 사람들과의 수익률 경쟁",
  buttonLabel: "Get started",
  imgStart: true,
  // img: require("../../images/svg1.svg"),
  //alt: "Frog",
  dark: true,
  primary: true,
  darkText: true,
  link: "/about",
};

export const homeObjTwo = {
  id: "discover",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "자기에게 적합한 ETF 탐색",
  headline: " 분산 투자가 가능해 보다 안정적인 상장지수펀드(ETF)",
  description: "분산 투자가 가능해 보다 안정적인 상장지수펀드(ETF) ETF는 거래소에 상장돼 주식과 똑같이 거래할 수 있는 펀드다.",
  buttonLabel: "Learn More",
  imgStart: true,
  // img: require("../../images/svg2.svg"),
  // alt: "discover",
  dark: true,
  primary: true,
  darkText: true,
  link: "/discover",
};

export const homeObjThree = {
  id: "chart",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "차트",
  headline: " 무한한 정보제공과 상장된 가상화폐의 서비스 가능 경로 정보 제공",
  description: "자유로운 차트 도구 사용으로 미래의 정확성 향상",
  buttonLabel: "Learn More",
  imgStart: true,
  dark: false,
  primary: false,
  darkText: true,
  link: "/coins",
};

export const homeObjFour = {
  id: "news",
  lightBg: true,
  lightText: true,
  lightTextDesc: true,
  topLine: "뉴스",
  headline: " 무한한 정보제공과 상장된 가상화폐의 서비스 가능 경로 정보 제공",
  description: "자유로운 차트 도구 사용으로 미래의 정확성 향상",
  buttonLabel: "Learn More",
  imgStart: true,
  dark: true,
  primary: false,
  darkText: true,
  link: "/news",
};

export const homeObjFive = {
  id: "signup",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "시장 동향 분석",
  headline: " 무한한 정보제공과 상장된 가상화폐의 서비스 가능 경로 정보 제공",
  description:
    "수많은 정보들은 한군데 모아 앞으로의 시장 방향의 중심을 찾을수있도록 도와드립니다.",
  buttonLabel: "Start Now",
  imgStart: false,
  // img: require("../../images/svg2.svg"),
  // alt: "paper",
  dark: true,
  primary: true,
  darkText: true,
  link: "/signup",
};
